spring:
  application:
    name: Image uploader
  cloud:
    gcp:
      credentials:
        location: classpath:credentials.json

server:
  port: 8081
  servlet:
    context-path: /image-uploader

gcs-resource:
  bucket: bucket-name
  path: images/